# Generated by Django 5.1.15 on 2026-05-24 22:06

import apps.core.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NichePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('ticket_label', models.CharField(default='Atendimento', help_text="Como o nicho chama um 'atendimento'? (ex.: 'Ensaio', 'Sessão', 'OS')", max_length=40)),
                ('suggested_services', models.JSONField(default=list, help_text='Lista de objetos {name, base_price, duration_minutes}')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('profile_level', models.CharField(choices=[('L1', 'Freelancer'), ('L2', 'Estúdio'), ('L3', 'Estúdio + Loja')], default='L1', max_length=2)),
                ('settings', models.JSONField(default=dict, help_text='Configs flexíveis: default_signal_pct, working_hours, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.nichepreset')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('manager', 'Gerente'), ('employee', 'Funcionário'), ('viewer', 'Visualizador')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('accepted_invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='accounts.invitation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo',
                'verbose_name_plural': 'vínculos',
                'unique_together': {('company', 'user')},
            },
            managers=[
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
    ]
