# Generated by Django 5.1.15 on 2026-05-24 23:37

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG/JPG, idealmente quadrado (≥ 256px). Opcional.', null=True, upload_to=apps.companies.models._company_logo_path, verbose_name='logo'),
        ),
    ]
