# Generated by Django 5.1.15 on 2026-05-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashflow', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Preenchido em movimentos automáticos. Vazio em manuais.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_entry', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['company', 'occurred_at'], name='cashflow_ca_company_4d8cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowentry',
            index=models.Index(fields=['company', 'direction', 'occurred_at'], name='cashflow_ca_company_9ac083_idx'),
        ),
    ]
