# Generated by Django 5.1.15 on 2026-05-24 22:41

import apps.core.managers
import apps.documents.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('receipt', 'Cupom de serviço'), ('contract', 'Contrato')], max_length=20, verbose_name='tipo')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='arquivo')),
                ('public_token', models.CharField(default=apps.documents.models._new_public_token, editable=False, max_length=48, unique=True, verbose_name='token público')),
                ('public_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
    ]
