# Generated by Django 5.1.15 on 2026-05-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tickets.ticket', verbose_name='atendimento'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'kind'], name='documents_d_company_cd49bc_idx'),
        ),
    ]
