# Generated by Django 5.1.15 on 2026-05-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niche_slug', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, help_text='utm_source ou referrer', max_length=40)),
            ],
            options={
                'verbose_name': 'interesse na waitlist',
                'verbose_name_plural': 'interesses na waitlist',
                'ordering': ['-created_at'],
                'unique_together': {('niche_slug', 'email')},
            },
        ),
    ]
