# Generated by Django 5.1.15 on 2026-05-24 22:41

import apps.core.managers
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('deposit', 'Sinal'), ('balance', 'Saldo'), ('full', 'Pagamento único'), ('refund', 'Devolução')], max_length=10, verbose_name='tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vence em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('method', models.CharField(blank=True, choices=[('cash', 'Dinheiro'), ('pix', 'PIX'), ('card', 'Cartão'), ('transfer', 'Transferência'), ('other', 'Outro')], max_length=10, verbose_name='método')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['due_date', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
    ]
