# Generated by Django 5.1.15 on 2026-05-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.ticket', verbose_name='atendimento'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'status', 'due_date'], name='payments_pa_company_da5603_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'ticket'], name='payments_pa_company_056c15_idx'),
        ),
    ]
