# Generated by Django 5.1.15 on 2026-05-24 22:41

import apps.core.managers
import apps.tickets.models
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.tickets.models._generate_ticket_code, editable=False, max_length=20, unique=True, verbose_name='código')),
                ('status', models.CharField(choices=[('draft', 'Orçamento'), ('confirmed', 'Confirmado'), ('in_progress', 'Em execução'), ('completed', 'Concluído'), ('finalized', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='agendado para')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duração (min)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='local')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='dados extras')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='clients.client', verbose_name='cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'atendimento',
                'verbose_name_plural': 'atendimentos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_items', to='catalog.service')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.ticket', verbose_name='atendimento')),
            ],
            options={
                'verbose_name': 'item do atendimento',
                'verbose_name_plural': 'itens do atendimento',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tickets.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'históricos de status',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'status', 'scheduled_at'], name='tickets_tic_company_a2cf40_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'client'], name='tickets_tic_company_ca4fad_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', '-created_at'], name='tickets_tic_company_08f7e8_idx'),
        ),
    ]
