# Generated by Django 5.1.15 on 2026-05-24 22:41

import apps.core.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='título')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='início')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('is_blocking', models.BooleanField(default=False, help_text='True para folga/almoço/indisponibilidade.', verbose_name='bloqueia agenda')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'evento na agenda',
                'verbose_name_plural': 'eventos na agenda',
                'ordering': ['starts_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
    ]
