# Generated by Django 5.1.15 on 2026-05-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event', to='tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['company', 'starts_at'], name='scheduling__company_e698ec_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleevent',
            index=models.Index(fields=['company', 'starts_at', 'ends_at'], name='scheduling__company_975c05_idx'),
        ),
    ]
