# Generated by Django 5.1.15 on 2026-05-24 22:41

import apps.core.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'name'], name='clients_cli_company_7c10e0_idx'), models.Index(fields=['company', '-created_at'], name='clients_cli_company_93d28a_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
    ]
