# Generated by Django 5.1.15 on 2026-05-24 22:41

import apps.core.managers
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('stock', models.IntegerField(default=0, verbose_name='estoque')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'sku'], name='catalog_pro_company_cbcbcc_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='preço base')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duração (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='companies.company')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='catalog_ser_company_376f9b_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', apps.core.managers.AllObjectsManager()),
            ],
        ),
    ]
